version: '3'
services:
  wvupsmdb:
    build: WVUPSM.DAL/
    image: lcbutch/wvupsmdb:prod
  wvupsmapi:
    build: WVUPSM.Service/WVUPSM.Service/
    image: lcbutch/wvupsmapi:prod
    depends_on:
      - wvupsmdb
    restart: always
    ports:
      - "3000:80"
  wvupsmmvc:
    build: WVUPSM.MVC/WVUPSM.MVC/
    image: lcbutch/wvupsmmvc:prod
    depends_on:
      - wvupsmdb
      - wvupsmapi
    restart: always
    ports:
      - "80:80"

networks:
  default:
    external:
      name: nat
