# Created by: Levi Butcher
# Sets up our DB to be used for the Service and MVC

From microsoft/mssql-server-windows-developer as final
WORKDIR app
Expose 1433
ENV sa_password=Develop@90
ENV ACCEPT_EULA=Y
WORKDIR /
