# Created by: Levi Butcher
# Sets up our DB to be used for the Service and MVC

From microsoft/mssql-server-linux as final
WORKDIR app
Expose 1433
ENV SA_PASSWORD=Develop@90
ENV ACCEPT_EULA=Y
WORKDIR /
